# Generated by Django 3.1.6 on 2021-02-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('have_password', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_connection', to='chat.room')),
            ],
        ),
    ]
