# Generated by Django 3.1.6 on 2021-02-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='have_password',
        ),
    ]
