# Generated by Django 3.1.6 on 2021-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210223_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
    ]
