# Generated by Django 3.1.6 on 2021-02-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210223_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_in_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_message', to='chat.room'),
        ),
    ]
